# Generated by Django 4.1.3 on 2022-12-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_test_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
