# Generated by Django 4.1.3 on 2022-12-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_test_drf', '0002_alter_entity_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='value',
            field=models.IntegerField(),
        ),
    ]
